[总体错误] Episode 54 失败: Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [1, 1, 8, 15, 15]
Traceback (most recent call last):
  File "train.py", line 186, in run_training
    agent.update_from_buffer(episode_buffer, episode)
  File "/app/agent/ppo_agent.py", line 232, in update_from_buffer
    self.update(current_episode)
  File "/app/agent/ppo_agent.py", line 290, in update
    logits_list, value, hidden_state = self.model(s_t, m_t, hidden_state)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/app/model/ppo_model.py", line 72, in forward
    map_feat = self.cnn(full_map)  # (B, cnn_output_size)，**不是 per-unit 的！**
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/container.py", line 215, in forward
    input = module(input)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [1, 1, 8, 15, 15]


